# Generated by Django 4.2.8 on 2024-04-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decorations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='image/decorations/')),
            ],
            options={
                'verbose_name': 'Вид десерта',
                'verbose_name_plural': 'Виды десертов',
            },
        ),
        migrations.CreateModel(
            name='Fillings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='image/fillings/')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Пример начинки',
                'verbose_name_plural': 'Примеры начинок',
            },
        ),
        migrations.CreateModel(
            name='ExampleFilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='image/fillings/example/')),
                ('title', models.CharField(max_length=150)),
                ('fillings', models.ManyToManyField(blank=True, related_name='examples', to='desserts.fillings')),
            ],
            options={
                'verbose_name': 'Начинка',
                'verbose_name_plural': 'Начинки',
            },
        ),
        migrations.CreateModel(
            name='ExampleDecoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='image/decorations/example/')),
                ('examples', models.ManyToManyField(blank=True, related_name='decorations', to='desserts.decorations')),
            ],
            options={
                'verbose_name': 'Десерт',
                'verbose_name_plural': 'Десерты',
            },
        ),
    ]
